name: React CI

on: [push]

jobs:
  build:
    name: Build and unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.1
      - uses: actions/setup-node@v6.0.0
        with:
          node-version: '22'
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
  
  # cypress:
  #   name: Cypress test
  #   needs: [build]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v5.0.1
  #     - name: Cache firebase emulators
  #       uses: actions/cache@v4.3.0
  #       with:
  #         path: ~/.cache/firebase/emulators
  #         key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('~/.cache/firebase/emulators/**') }}

  #     - run: npm install -g firebase-tools

  #     - uses: cypress-io/github-action@v6.10.4
  #       with:
  #         build: npm run build
  #         start: npm run em:run
  #         wait-on: http://localhost:3000

  deploy:
    name: Firebase deploy
    needs: [build, cypress]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.1
      - uses: actions/setup-node@v6.0.0
        with:
          node-version: '22'
      - run: npm install
      - run: npm run build
      - run: npm install -g firebase-tools
      - run: firebase deploy --token "${{ secrets.FIREBASE_DEPLOY_TOKEN }}" --non-interactive